# Generated by Django 5.1.7 on 2025-09-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_productcategory_trackedproduct_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedproduct",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
